"""
Trains a real-time hazard/failure classifier on the IIoT edge computing dataset,
using only Temperature, Pressure, and Vibration -- the three features our app's
sensors actually measure -- so the model is honestly deployable against live
sensor readings (no features we can't provide at inference time).

Exports weights as JSON for a small MLP forward pass ported to TypeScript.
"""
import json
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, roc_auc_score, f1_score

df = pd.read_csv("attached_assets/iiot_dataset/iiot_edge_computing_dataset.csv")

FEATURES = ["Temperature", "Pressure", "Vibration", "Fuzzy_PID_Output"]
X = df[FEATURES].values
y = df["Predicted_Failure"].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

scaler = StandardScaler()
X_train_s = scaler.fit_transform(X_train)
X_test_s = scaler.transform(X_test)

clf = MLPClassifier(hidden_layer_sizes=(16,), activation="relu", max_iter=2000, random_state=42)
clf.fit(X_train_s, y_train)

pred = clf.predict(X_test_s)
proba = clf.predict_proba(X_test_s)[:, 1]
acc = accuracy_score(y_test, pred)
auc = roc_auc_score(y_test, proba)
f1 = f1_score(y_test, pred)
print(f"Test accuracy: {acc:.4f}  AUC: {auc:.4f}  F1: {f1:.4f}")

# MLPClassifier with one hidden layer has coefs_ = [W1 (in x hid), W2 (hid x out)]
# intercepts_ = [b1 (hid,), b2 (out,)]
W1, W2 = clf.coefs_
b1, b2 = clf.intercepts_

weights = {
    "features": FEATURES,
    "scalerMean": scaler.mean_.tolist(),
    "scalerScale": scaler.scale_.tolist(),
    "W1": W1.tolist(),
    "b1": b1.tolist(),
    "W2": W2.tolist(),
    "b2": b2.tolist(),
    "metrics": {"accuracy": acc, "auc": auc, "f1": f1, "testSize": len(y_test)},
}

out_path = "artifacts/api-server/src/ml/iiot-hazard-model.ts"
import os
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w") as f:
    f.write(
        "// Auto-generated by ml/train_iiot_hazard_model.py. Do not hand-edit.\n"
        "export const iiotHazardModel = "
        + json.dumps(weights)
        + " as const;\n"
    )

print(f"Saved model weights to {out_path}")
