"""
Trains a Remaining Useful Life (RUL) regressor on the NASA C-MAPSS FD001
turbofan engine degradation dataset. Exports weights as JSON for a small MLP
forward pass ported to TypeScript, used to drive the live "Engine Health" page.
"""
import json
import os
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error

COLS = ["unit", "cycle", "op1", "op2", "op3"] + [f"s{i}" for i in range(1, 22)]

train = pd.read_csv("attached_assets/turbofan_dataset/train_FD001.txt", sep=r"\s+", header=None, names=COLS)
test = pd.read_csv("attached_assets/turbofan_dataset/test_FD001.txt", sep=r"\s+", header=None, names=COLS)
rul_truth = pd.read_csv("attached_assets/turbofan_dataset/RUL_FD001.txt", sep=r"\s+", header=None, names=["RUL"])

# Training RUL label: cycles remaining until that unit's last recorded cycle.
max_cycle = train.groupby("unit")["cycle"].max().rename("max_cycle")
train = train.join(max_cycle, on="unit")
train["RUL"] = train["max_cycle"] - train["cycle"]
# Cap RUL at 130 -- degradation is roughly flat before this point, a standard trick
# for this dataset that keeps the regressor from being dominated by early-life noise.
train["RUL"] = train["RUL"].clip(upper=130)

# Drop sensors that are ~constant for FD001 (single operating condition) -- they
# carry no signal and would just add noise to the model.
sensor_cols = [f"s{i}" for i in range(1, 22)]
variances = train[sensor_cols].var()
useful_sensors = variances[variances > 1e-6].index.tolist()
FEATURES = ["op1", "op2", "op3"] + useful_sensors
variances_op = train[["op1", "op2", "op3"]].var()
FEATURES = [c for c in FEATURES if c not in variances_op[variances_op <= 1e-6].index.tolist()]

print(f"Using {len(FEATURES)} features: {FEATURES}")

X_train = train[FEATURES].values
y_train = train["RUL"].values

# Test set: only the last cycle per unit has a ground-truth RUL (from RUL_FD001.txt).
last_cycle = test.groupby("unit").tail(1).reset_index(drop=True)
X_test = last_cycle[FEATURES].values
y_test = rul_truth["RUL"].values

scaler = StandardScaler().fit(X_train)
X_train_s = scaler.transform(X_train)
X_test_s = scaler.transform(X_test)

reg = MLPRegressor(hidden_layer_sizes=(32, 16), activation="relu", max_iter=2000, random_state=42, early_stopping=True)
reg.fit(X_train_s, y_train)

pred = reg.predict(X_test_s)
rmse = mean_squared_error(y_test, pred) ** 0.5
mae = mean_absolute_error(y_test, pred)
print(f"Test RMSE: {rmse:.2f} cycles  MAE: {mae:.2f} cycles (label capped at 130)")

W1, W2, W3 = reg.coefs_
b1, b2, b3 = reg.intercepts_

weights = {
    "features": FEATURES,
    "scalerMean": scaler.mean_.tolist(),
    "scalerScale": scaler.scale_.tolist(),
    "ruCap": 130,
    "W1": W1.tolist(), "b1": b1.tolist(),
    "W2": W2.tolist(), "b2": b2.tolist(),
    "W3": W3.tolist(), "b3": b3.tolist(),
    "metrics": {"rmse": rmse, "mae": mae, "testUnits": len(y_test)},
}

out_path = "artifacts/api-server/src/ml/turbofan-rul-model.ts"
os.makedirs(os.path.dirname(out_path), exist_ok=True)
with open(out_path, "w") as f:
    f.write(
        "// Auto-generated by ml/train_turbofan_rul_model.py. Do not hand-edit.\n"
        "export const turbofanRulModel = "
        + json.dumps(weights)
        + " as const;\n"
    )
print(f"Saved model weights to {out_path}")

# Also export a handful of real test-unit trajectories so we can replay live
# telemetry for a small fleet of demo "engines" instead of fabricating fake data.
demo_units = sorted(test["unit"].unique())[:6]
trajectories = {}
for u in demo_units:
    sub = test[test["unit"] == u].sort_values("cycle")
    trajectories[str(u)] = {
        "cycles": sub["cycle"].tolist(),
        "features": sub[FEATURES].values.tolist(),
        "finalTrueRUL": float(rul_truth.iloc[u - 1]["RUL"]),
    }

traj_path = "artifacts/api-server/src/ml/turbofan-demo-trajectories.ts"
with open(traj_path, "w") as f:
    f.write(
        "// Auto-generated by ml/train_turbofan_rul_model.py. Do not hand-edit.\n"
        "export const turbofanDemoTrajectories = "
        + json.dumps(trajectories)
        + " as const;\n"
    )
print(f"Saved {len(demo_units)} demo trajectories to {traj_path}")
